// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNnE7H-DCakKhisDGIU1xtp9TDx6uzaQ8',
    appId: '1:712677754253:web:7a665008eff30cbe5969c4',
    messagingSenderId: '712677754253',
    projectId: 'shhtudy-44b72',
    authDomain: 'shhtudy-44b72.firebaseapp.com',
    storageBucket: 'shhtudy-44b72.firebasestorage.app',
    measurementId: 'G-L9T3XMJHVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwZdr5yGxyt0wpH6UxeHTklNMkpGVNjoE',
    appId: '1:712677754253:android:eb5930be254b1ef75969c4',
    messagingSenderId: '712677754253',
    projectId: 'shhtudy-44b72',
    storageBucket: 'shhtudy-44b72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6Z00gw3gJ_BzTXQeegw5mjuRdanYRARA',
    appId: '1:712677754253:ios:3d3d5d811f7a50335969c4',
    messagingSenderId: '712677754253',
    projectId: 'shhtudy-44b72',
    storageBucket: 'shhtudy-44b72.firebasestorage.app',
    iosBundleId: 'com.example.shhtudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6Z00gw3gJ_BzTXQeegw5mjuRdanYRARA',
    appId: '1:712677754253:ios:3d3d5d811f7a50335969c4',
    messagingSenderId: '712677754253',
    projectId: 'shhtudy-44b72',
    storageBucket: 'shhtudy-44b72.firebasestorage.app',
    iosBundleId: 'com.example.shhtudyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNnE7H-DCakKhisDGIU1xtp9TDx6uzaQ8',
    appId: '1:712677754253:web:7a665008eff30cbe5969c4',
    messagingSenderId: '712677754253',
    projectId: 'shhtudy-44b72',
    authDomain: 'shhtudy-44b72.firebaseapp.com',
    storageBucket: 'shhtudy-44b72.firebasestorage.app',
    measurementId: 'G-L9T3XMJHVC',
  );
}
