spring:
  application:
    name: backend

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    url: jdbc:mysql://mysql:3306/shhtudy_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        connection:
          characterEncoding: utf8
          CharSet: utf8
          useUnicode: true

  mvc:
    async:
      request-timeout: 60000

  web:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"

  security:
    basic:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

server:
  port: ${SERVER_PORT:8080}
  tomcat:
    connection-timeout: 120000
    max-http-form-post-size: 20MB
  servlet:
    encoding:
      charset: UTF-8
      force: true

logging:
  level:
    com.shhtudy.backend: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs
    enabled: true

app:
  firebase:
    enabled: true
    config-file: ${FIREBASE_CONFIG_PATH}
    project-id: ${FIREBASE_PROJECT_ID}
    private-key-id: ${FIREBASE_PRIVATE_KEY_ID}
    private-key: ${FIREBASE_PRIVATE_KEY}
    client-email: ${FIREBASE_CLIENT_EMAIL}
    client-id: ${FIREBASE_CLIENT_ID}

jwt:
  secret: ${JWT_SECRET:local-dev-secret-123456}
  expiration: ${JWT_EXPIRATION:86400000}

volumes:
  - ./firebase/firebase-service-account.json:/app/firebase/firebase-service-account.json

